### ISSUE TITLE
Error while loading shared libraries: libsyntax.so

### ISSUE THREAD

**Issue by ngirard** [rust-dev-tools/cargo-src#251]
After doing `rustup update` then `cargo +nightly install --force cargo-src`, thus grabbing the very last version (v0.1.6), running `cargo src` gives:

`/home/ngirard/.cargo/bin/cargo-src: error while loading shared libraries: libsyntax-f2164304c18a5f01.so: cannot open shared object file: No such file or directory`

**Comment by nrc** [comment]
These should help: https://github.com/rust-dev-tools/cargo-src#troubleshooting
