### ISSUE TITLE
can't find crate rustc_parse

### ISSUE THREAD

**Issue by D1mon** [rust-dev-tools/cargo-src#266]
steps:
1) i usage nightly version (nightly-x86_64-unknown-linux-gnu)
2) rustup update (rust version 1.43.0-nightly (5d04ce67f 2020-02-13))
3) cargo install cargo-src

error:
rust/nightly/registry/src/github.com-1ecc6299db9ec823/rustdoc-highlight-0.1.10/src/lib.rs:19:1
extern crate rustc_parse;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
error: aborting due to previous error

**Comment by bjorn3** [comment]
Have you installed the `rustc-dev` component? (`rustup component add --toolchain nightly rustc-dev`)

**Comment by D1mon** [comment]
i run this command: `rustup component add --toolchain nightly rustc-dev`
same error

**Comment by D1mon** [comment]
sorry new error:
```
rust/nightly/registry/src/github.com-1ecc6299db9ec823/rustdoc-highlight-0.1.10/src/lib.rs:21:1
extern crate syntax_expand;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by bjorn3** [comment]
Looks like this needs to be updated for the latest nightly.

**Comment by D1mon** [comment]
`rustup component add --toolchain nightly rustc-dev`

> info: component 'rustc-dev' for target 'x86_64-unknown-linux-gnu' is up to date

**Comment by bjorn3** [comment]
I meant cargo-src, not the component.
